### ISSUE TITLE
AI America is Broken in the bad kind of way

### ISSUE THREAD

**Issue by Normieigess** [ravignir/RekMOD#1]
Obligatry sorry in advance for my English, not my 1st Lang. Pioneer unique unit that replace settler has strength of 5. Now the game AI will (and I cannot stress this enough) always escort their settler across the map. But because this UU have strength point, they can't be in one tile with their escort. Short story they won't settle city w pioneer. Even actually just start using them as another fighting unit in my other game. Maybe just removing that strength point will help? I dunno just making sure am playing against AI in their full potential or something. Just that for now.

**Comment by ravignir** [comment]
That's the point of the unit, it is just AI is broken in the base game, and irt can only settle with settlers.

**Comment by Normieigess** [comment]
Oh really? Never played the actual mod or real civ 5 itself actually, sorry
for my stupid

Pada tanggal Jum, 23 Apr 2021 17.16, ravignir ***@***.***>
menulis:
