### ISSUE TITLE
Mountains & shortcuts

### ISSUE THREAD

**Issue by krijnsent** [ravignir/RekMOD#11]
Love playing UnCiv with your mod, 3 findings:
- with 3.15.15, start a map with RekMOD and find that there are no mountains nor hills on the map. They do show up in the map editor, but not in a normal game. Without the mod, they do appear on the map.
- the P shortcut for building a Pasture/Plantation does not always work, seems mainly on sheep, but haven't found exactly when/where it happens that the game simply doesn't respond to it.
- Americans get a special settler, except from: starting settler & from goodie huts, I assume that should be different  (always a pioneer), but am not sure if that's moddable yet

**Comment by ravignir** [comment]
1: fixed
2: fixed
3: that's not possible yet
