### ISSUE TITLE
Mod doesn't show up anywhere after updating/downloading it

### ISSUE THREAD

**Issue by theNorthBeast** [ravignir/RekMOD#110]
This error shows up in the Locate mod errors tab:
Exception loading mod 'RekMOD':
Could not parse json of file TileResources.json
Error parsing JSON on line 554 near: "*ERROR*"],
},
{
"name": "Perfume",
"resourceType": "Luxury",
"before the Renaissance era

**Comment by SeventhM** [comment]
This bug is already fixed with https://github.com/ravignir/RekMOD/pull/111

Please wait until an owner of this mod accepts the pull request
