### ISSUE TITLE
Mod checker now whines about circular references in Promotions

### ISSUE THREAD

**Issue by SomeTroglodyte** [ravignir/RekMOD#122]
[Unciv #9694](https://github.com/yairm210/Unciv/pull/9694) flags RekMod some more, Warning level, for certain Promotions.

Unrelated - let's get them out of the way (may be outdated - didn't download freshly):
* Heal instantly - I suggest putting the row:0 back in, which would ensure it goes to the top in Promotion Picker
* You have no row/column at all with one exception - better remove that for consistency
* You're right they don't work as they used to - but you can still use them to juggle in which order "root" promotions - those without prerequisites - are placed. No numbers - alphabetic after translation. Some dependencies maybe go too much diagonally, and some tinkering with the numbers might help. Using one or the other should be enough.

`Ambition - Invulnerability - Restlessness`
The promotions in question all refer to each of the group as prerequisite including itself - a problem for the picker, hence the mod checker addition. Now I can imagine there's a purpose behind that - make them inaccessible unless you get one of them through other means first??? There must be another way - or we could think up a way to add metadata the picker can use and that can be made to silence the checker.

<details>

![image](https://github.com/ravignir/RekMOD/assets/63000004/c0e4fb87-148c-4f55-8304-73911c736add)

![image](https://github.com/ravignir/RekMOD/assets/63000004/195954ab-8d48-4771-994a-1280c0ae926e)

</details>

Last screenie shows the current impact on the picker - it needed to break the circles, so the prerequisite **colours** are unsymmetric over those three - the description on the bottom works independently.

**Comment by SeventhM** [comment]
Just now noticed this, Sorry (apparently I wasn't set to watching the repo... whoops). I've already been fixed the loop by now, so closing this.


> * You have no row/column at all with one exception

I'm not sure I know what you're referring to

> Now I can imagine there's a purpose behind that

From my understanding... No, it was just broken before and I never noticed. If someone wanted to do that, they should also give the unit `Mystic Blade`

> * Heal instantly - I suggest putting the row:0 back in

I'll look into that next time I update this mod
