### ISSUE TITLE
Leftover Great Writer icon from my tests

### ISSUE THREAD

**Issue by SomeTroglodyte** [ravignir/RekMOD#138]
Little detail - the yellow square on CityScreen intrigued me and I wanted to see how to get a proper icon in there. Turns out it's UnitIcons, not EmojiIcons, and it's pulled twice using two different ImageGetter methods...

To test, I used a little gimp of:
`-   [Feather](https://thenounproject.com/term/feather/1628/) By Eduardo Souza for Constitution`
...since the one in Unciv is only 50x50, and I wanted 100x100.

In case you wanna use it:
[Great Writer.png.zip](https://github.com/ravignir/RekMOD/files/13208109/Great.Writer.png.zip)
... otherwise simply close this.

**Comment by SeventhM** [comment]
I should probably search for myself and not bother others, but, uh... You wouldn't happen to, uhhhh... Have one for Great Musicians... Would you?

**Comment by SeventhM** [comment]
Violin is definitely better in context than violinist

Tbh, I have no practice looking for anything yet, and would probably end up using paint3D out of laziness (and to save space on my flash drive) so I got no experience here
