### ISSUE TITLE
Sea trade route

### ISSUE THREAD

**Issue by r4ffz4hn** [ravignir/RekMOD#141]
I noticed today I do not get any bonus from sea trade routes (production) on atoll tiles ? Wondering if but or feature...

**Comment by SeventhM** [comment]
Production trade routes don't give their base production unless the city has a workshop. Check if your city had a workshop first

**Comment by r4ffz4hn** [comment]
That was new to me, I always gained 2 production + from a sea trade route production even if no workshop was built in the city. Also just tested in a very slow trial of marathon game and I get the bonus production now even if my workshop still takes 7 turns to build ? Is it the workshop technology that triggers the bonus ? I'm confused at this stage

**Comment by SeventhM** [comment]
You get +2 production starting in the classical era, another +2 starting from the Industrial era, and another+2 starting in the modern era. However, you get +6 if the city has a built workshop

**Comment by r4ffz4hn** [comment]
Thank you for clarifying. I was trying to use the trade route in the ancient era and was quite surprised yielding no effect. 
I suppose this can be closed / deleted then
