### ISSUE TITLE
Just a small request

### ISSUE THREAD

**Issue by ShineFox07** [ravignir/RekMOD#148]
Me and my friend really need Euskadi or something like that for the Basque nation. I kindly ask you to add them and I'm very sorry for the trouble.
thank you for your attention and time.

**Comment by SeventhM** [comment]
Unfortunately, this is focused on only adding elements from the civ 5 mod [lekmod](https://docs.google.com/document/d/18tsjg2C1wKA7I41GktDRr6R83eUrhn4FHi9EUEtpKvI/edit#heading=h.sgkkio8aa458). You are more than welcome to create your own extension mod for rekmod, but any material not in lekmod will not be added without a necessary reasoning towards doing so
