### ISSUE TITLE
Great Writing Slots producing Great Works of Writing

### ISSUE THREAD

**Issue by tastyricin** [ravignir/RekMOD#170]
![Screenshot_20240303-171711_Unciv](https://github.com/ravignir/RekMOD/assets/157823768/908976c2-53b5-4af0-9271-ae972b861b15)

Upon purchasing or constructing a Great Writing Slot, it starts producing more GW of Writing by itself. Those provide policies, enabling players to construct a Utopia Project in 1100 AD.

**Comment by SeventhM** [comment]
I will need a bit more information to understand what the issue is. What version of Unciv are you playing on and does this issue continue if you restart the game?

**Comment by SeventhM** [comment]
Actually, nevermind, you said you can build Utopia project. This is a bug of Unciv version 4.10.14. Please either downgrade to an earlier version or upgrade to 4.10.15

**Comment by tastyricin** [comment]
Alright, thanks!
