### ISSUE TITLE
Cultural Victory bug

### ISSUE THREAD

**Issue by actarus000** [ravignir/RekMOD#171]
![Screenshot_2024-03-03-23-30-40-019_com unciv app](https://github.com/ravignir/RekMOD/assets/942604/c26dac84-32a5-4d74-b0ed-8aee96f51baf)
India won a Cultural Victory, which requires 31 policies, yet India doesn't have them.

**Comment by SeventhM** [comment]
This is a bug with Unciv version 4.10.14. Please either downgrade to an earlier version or upgrade to 4.10.15
