### ISSUE TITLE
Great works not affected by Aesthetics policies

### ISSUE THREAD

**Issue by O-spin** [ravignir/RekMOD#179]
Have been playing for a while, and never bothered to take aesthetics because of tourism not being implemented, but now that I found a reasonable opportunity to take it, it seems like the policies don't work? 

On Turn 87 I take "Artistic Genius" which should grant my 2 filled Great Library Great Writing Slots +3 science. It does not.
[Byzantium Turn 87 bugged.txt](https://github.com/ravignir/RekMOD/files/14933760/Byzantium.Turn.87.bugged.txt)

**Comment by SeventhM** [comment]
Thanks for the reminder. Took an embarrassingly long time to figure out the issue

**Comment by SeventhM** [comment]
Closing as fixed by #180
