### ISSUE TITLE
All cities can build courthouse

### ISSUE THREAD

**Issue by O-spin** [ravignir/RekMOD#181]
It seems like "Can only be built in Annexed cities" on courthouse is broken.

![image](https://github.com/ravignir/RekMOD/assets/78930692/8e31f940-a126-443e-8a92-93bc724b8690)

**Comment by SeventhM** [comment]
What version of Unciv are you running?

**Comment by O-spin** [comment]
Updated to 4.11.4, now works as intended. I was running 4.10.13 before.
