### ISSUE TITLE
Difficulty

### ISSUE THREAD

**Issue by SHypoleac** [ravignir/RekMOD#192]
Hi, what do you think about difficulty level of this game? Isn't it much easier than real civilization? I think that basic version has enough shortcomings in AI, but this mod makes the game even simpler. For me its like Emperor - Very Easy, Immortal - Normal, and Deity - Very Hard, but we have 8 levels of difficulty and we should use them. On Emperor level mini you can just end the game before middle ages -
![quickimperator](https://github.com/ravignir/RekMOD/assets/153895174/bd47590e-f835-4749-877b-867e45a0df1f)
And on Immortal big im leading without any wars, when AI has the greatest shortcomings in this.
![hung](https://github.com/ravignir/RekMOD/assets/153895174/f9ce6842-06e5-412b-81b6-db3090b59a18)
Maybe we should fix it somehow?

**Comment by SeventhM** [comment]
The difficulty file line for line matches the one in G&K. At most, I could update it to match the BNW values (as the AIs changed in that update). However, I have 3 problems with that
1. I need a new unique to set the difficulty that the AIs play on
2. If I had such a unique, then it would undoubtedly make the AIs easier not harder 
3. Most of the ease in AI difficulty is an Unciv problem, not this mod's problem. Unless your suggestion is to blindly attempt to add difficulty into this mod without knowing what I'm doing, very little I could edit here would actually affect the mod's difficulty. So I kinda don't understand why you're making an issue here and not for Unciv itself

**Comment by SHypoleac** [comment]
I'm very sorry for asking, I hope I didn't disturb your brilliant concentration, but couldn't we just edit difficulties.json? I just wanted to ask the players if they had similar feelings

**Comment by SeventhM** [comment]
> but couldn't we just edit difficulties.json?

This would have a mechanical impact on the mod, so no. Anything that have a mechanical difference from Lekmod and cannot be justified through limitations or clear errors in Lekmod is off limits. If you want to address this, please do so on your own fork

Keep in mind, I doubt editing the difficulties file really will do what you want. Feel free to test on your own fork, but I doubt it'll go well for you
