### ISSUE TITLE
The caravan does not lift the fog of war

### ISSUE THREAD

**Issue by Semigradsky** [ravignir/RekMOD#193]
![Screenshot_2024-04-22-00-16-11-936_com unciv app](https://github.com/ravignir/RekMOD/assets/1198848/2af0cbf2-94cd-4d6d-9158-a70487de2ea1)

![Screenshot_2024-04-22-00-16-21-811_com unciv app](https://github.com/ravignir/RekMOD/assets/1198848/f498844c-1766-434a-9eb4-9087f9baa122)

**Comment by SHypoleac** [comment]
on civilopedia, the caravan has a 'no sight' feature written on it, so I guess this is the intended functionality

**Comment by SeventhM** [comment]
Not clearing the fog is intended. Being able to move into the fog and still not see the unit is not

**Comment by Semigradsky** [comment]
Unciv 4.11.7
![Screenshot_2024-05-01-20-56-43-961_com unciv app](https://github.com/ravignir/RekMOD/assets/1198848/1939dfa0-6eb5-42e5-acff-8fb643245347)
