### ISSUE TITLE
Tile must be under the fog

### ISSUE THREAD

**Issue by Semigradsky** [ravignir/RekMOD#231]
The barbarian was captured my settler on previous turn. Now I see him and settler but there are no my units near.

![Screenshot_20241128_235102](https://github.com/user-attachments/assets/ab3d4c1b-722d-4de9-a6d5-6de314c309ed)

**Comment by yairm210** [comment]
That's a forest+hill so it's higher, and can be seen this far away. Working as expected.

**Comment by SeventhM** [comment]
Huh. I was going to write that off as low priority, but something to look at later". Neat
