### ISSUE TITLE
City-states don't provide their respective bonuses

### ISSUE THREAD

**Issue by PangXH842** [ravignir/RekMOD#37]
For example, Geneva does not provide any faith when allied. Same with Florence, but with culture.

PS: You also forgot to edit the biography of Greece. It's still about Alexander.

Edit: It worked ok in the base game without mods.

**Comment by PangXH842** [comment]
I've found out that the "Indulgences" enhancer belief doesn't work as well. It should provide +1 Production, +1 Food, +1 Gold, +1 Culture and +1 Faith in all cities. I think it is somehow related to this kind of issue. 
Military city states gift units as usual, but cultural, religious, maritime and merchantile city states all don't provide bonuses.

**Comment by ravignir** [comment]
Sorry, I am too lazy to fix this. You can submit PR tho.
