### ISSUE TITLE
Being able to get Great General with Macedonia Great General 

### ISSUE THREAD

**Issue by BetonowyMur** [ravignir/RekMOD#61]
Happens after destroying enemy cities, i think it shouldnt happen because Macedonia already does have upgraded Great General?
![Screenshot_20220420-152854](https://user-images.githubusercontent.com/50698170/164259870-0a8a7ee9-129f-4793-b20c-d48b9b85b8cf.png)

**Comment by SeventhM** [comment]
I missed this, but have no clue if this is still relevant. Closing
