### ISSUE TITLE
About the "Ignores terrain cost" promotion

### ISSUE THREAD

**Issue by NeoCurious** [ravignir/RekMOD#64]
There are some mods (especially the mods that are related or have to do with Scouts) that have conflict with RekMOD base because of the absence of that "s", since both the God&Kings and Vanilla have the name "Ignore terrain cost" while this mod have the name "Ignores terrain cost".

Maybe consider adding the "Ignore terrain cost" back as a separate promotion with "Ignores terrain cost" (since there might be other mods that use this) to have more compatibility with other mods since, unlike "Besiege" promotion, it's not a promotion that you can pick.

**Comment by Thienanbad** [comment]
> There are some mods (especially the mods that are related or have to do with Scouts) that have conflict with RekMOD base because of the absence of that "s", since both the God&Kings and Vanilla have the name "Ignore terrain cost" while this mod have the name "Ignores terrain cost".
> 
> Maybe consider adding the "Ignore terrain cost" back as a separate promotion with "Ignores terrain cost" (since there might be other mods that use this) to have more compatibility with other mods since, unlike "Besiege" promotion, it's not a promotion that you can pick.

Have fixed into Ignore.... Please close this issue
