### ISSUE TITLE
Feature suggestion to put collective rule above republic

### ISSUE THREAD

**Issue by logicminimal** [ravignir/RekMOD#7]
it is this way in vanilla unciv. i dont know if it is this way in the original civ 5

**Comment by ravignir** [comment]
yes, it is like this in civ5.
![img](https://user-images.githubusercontent.com/30041793/120902476-f5dc6380-c640-11eb-8eeb-9fb08ac88dbc.png)

**Comment by logicminimal** [comment]
> yes, it is like this in civ5.
> ![img](https://user-images.githubusercontent.com/30041793/120902476-f5dc6380-c640-11eb-8eeb-9fb08ac88dbc.png)
> 

it was this way in the game with dlc as far as i can remember

**Comment by logicminimal** [comment]
> > yes, it is like this in civ5.
> > ![img](https://user-images.githubusercontent.com/30041793/120902476-f5dc6380-c640-11eb-8eeb-9fb08ac88dbc.png)
> > 
> 
> it was this way in the game with dlc as far as i can remember, is rekmod aiming to replicate dlcs as well?

**Comment by ravignir** [comment]
Yes, rekmod replicates DLCs and adds new content. It is based on Lekmod for civ5.
