### ISSUE TITLE
Mod errors 

### ISSUE THREAD

**Issue by Alucard0Reborn** [ravignir/RekMOD#86]
Scout obsoletes at tech Scientific Theory, and therefore Steam Power for its upgrade Airship may not yet be researched!
Apedemaks Bow obsoletes at tech Scientific Theory, and therefore Steam Power for its upgrade Airship may not yet be researched!
Pictish Warrior obsoletes at tech Civil Service, and therefore Iron Working for its upgrade Swordsman may not yet be researched!
Pictish Swordsman obsoletes at tech Civil Service, and therefore Steel for its upgrade Longswordsman may not yet be researched!
Dromon obsoletes at tech Astronomy, and therefore Navigation for its upgrade Frigate may not yet be researched!
Baghlah obsoletes at tech Astronomy, and therefore Navigation for its upgrade Frigate may not yet be researched!
Samurai obsoletes at tech Gunpowder, and therefore Rifling for its upgrade Rifleman may not yet be researched!
Pikeman obsoletes at tech Gunpowder, and therefore Metallurgy for its upgrade Lancer may not yet be researched!
Pestininkas obsoletes at tech Gunpowder, and therefore Metallurgy for its upgrade Lancer may not yet be researched!
Ulan obsoletes at tech Gunpowder, and therefore Metallurgy for its upgrade Lancer may not yet be researched!
Great War Infantry obsoletes at tech Plastics, and therefore Electronics for its upgrade Infantry may not yet be researched!
Ski Infantry obsoletes at tech Plastics, and therefore Electronics for its upgrade Infantry may not yet be researched!
Force Publique obsoletes at tech Plastics, and therefore Electronics for its upgrade Infantry may not yet be researched!
Kuva-yi Milliye obsoletes at tech Plastics, and therefore Electronics for its upgrade Infantry may not yet be researched!
Voortrekker obsoletes at tech Plastics, and therefore Electronics for its upgrade Infantry may not yet be researched!

**Comment by ZorlinShape** [comment]
For clarity:

Forge's unique "[+15]% Production when constructing [Spaceship part] buildings [in this city]" contains parameter Spaceship part, which does not fit parameter type buildingFilter !
Blast Furnace's unique "[+15]% Production when constructing [Spaceship part] buildings [in this city]" contains parameter Spaceship part, which does not fit parameter type buildingFilter !
Spaceship Factory's unique "[+50]% Production when constructing [Spaceship Part] buildings [in this city]" contains parameter Spaceship Part, which does not fit parameter type buildingFilter !
Hubble Space Telescope's unique "[+200]% Production when constructing [Spaceship part] buildings [in this city]" contains parameter Spaceship part, which does not fit parameter type buildingFilter !
Scout obsoletes at tech Scientific Theory, and therefore Steam Power for its upgrade Airship may not yet be researched!
Apedemaks Bow obsoletes at tech Scientific Theory, and therefore Steam Power for its upgrade Airship may not yet be researched!
Pictish Warrior obsoletes at tech Civil Service, and therefore Iron Working for its upgrade Swordsman may not yet be researched!
Pictish Swordsman obsoletes at tech Civil Service, and therefore Steel for its upgrade Longswordsman may not yet be researched!
Dromon obsoletes at tech Astronomy, and therefore Navigation for its upgrade Frigate may not yet be researched!
Baghlah obsoletes at tech Astronomy, and therefore Navigation for its upgrade Frigate may not yet be researched!
Samurai obsoletes at tech Gunpowder, and therefore Rifling for its upgrade Rifleman may not yet be researched!
Pikeman obsoletes at tech Gunpowder, and therefore Metallurgy for its upgrade Lancer may not yet be researched!
Pestininkas obsoletes at tech Gunpowder, and therefore Metallurgy for its upgrade Lancer may not yet be researched!
Ulan obsoletes at tech Gunpowder, and therefore Metallurgy for its upgrade Lancer may not yet be researched!
Great War Infantry obsoletes at tech Plastics, and therefore Electronics for its upgrade Infantry may not yet be researched!
Ski Infantry obsoletes at tech Plastics, and therefore Electronics for its upgrade Infantry may not yet be researched!
Force Publique obsoletes at tech Plastics, and therefore Electronics for its upgrade Infantry may not yet be researched!
Kuva-yi Milliye obsoletes at tech Plastics, and therefore Electronics for its upgrade Infantry may not yet be researched!
Voortrekker obsoletes at tech Plastics, and therefore Electronics for its upgrade Infantry may not yet be researched!

**Comment by RealBamboolord** [comment]
@ZorlinShape I could fix this, I will copy from base game
